# Desmostración de Linalg en Python #
### Diego Correa ###
### Jose Ortega ###

La librería **linalg** que se encuentra en **numpy** se especializa en algebra lineal con matrices y vectores provistos por numpy.

## Determinante de una matriz ##
Dentro de linalg la funciona para calcular el determinante es _det_ la cual recibe como argumento la matriz sobre la cual se va a operar
Ejemplo:
```python
import numpy as np
a = np.array([[25, 35, 12, 4], [23, 74, 2, 64], [89, 4, 23, 56], [48, 17, 6, 99]])
```

In [30]:
import numpy as np
a = np.array([[25, 35, 12, 4], [23, 74, 2, 64], [89, 4, 23, 56], [48, 17, 6, 99]])
print("a:")
print(a)

a:
[[25 35 12  4]
 [23 74  2 64]
 [89  4 23 56]
 [48 17  6 99]]


```python
# Para usar linalg se pude invocar desde la referencia que se tiene de numpy
d = np.linalg.det(a)
# o usar un nuevo alias para linalg y luego usarlo
import numpy.linalg as ln
d = ln.det(a)
```

In [32]:
import numpy.linalg as ln
d = ln.det(a)
print("d = "+str(d))

d = -1547321.0


## Valores propios de una matriz ##
Para calcular los valores propios de una matriz linalg ofrece la funcion _eigvals_ la cual recibe una matriz sobre la cual se va a operar.

Ejemplo:
```python
a = np.array([[25, 35, 12, 4], [23, 74, 2, 64], [89, 4, 23, 56], [48, 17, 6, 99]])
b = ln.eigvals(a)
```

In [36]:
print("Valores propios de a:")
print(ln.eigvals(a))

Valores propios de a:
[ 143.53403049 +0.j           -5.31345822 +0.j           41.38971387+17.76889942j
   41.38971387-17.76889942j]


## Solucion a sistemas de ecuaciones ##
Para resolver sistemas de ecuaciones lineales linalg ofrece la funcion _solve_ la cual recibe como primer parametro las matrices de los coeficientes del sistema y como segundo los valores de cada ecuacion, y su retorno es el vector de valores para las incognitas en la ecuacion:

Ejemplo:

$ 2x_{1} + x_{2} + x_{3} = 5 $

$ 4x_{2} - 6x_{3} = -2 $

$ -2x_{1} + 7x_{2} + 2x_{3} = 9 $

Este sistema de ecuaciones se puede representar en numpy como:

```python
A = np.array([[2, 1, 1], [0, 4, -6], [-2, 7, 2]])
b = np.array([5, -2, 9])
```




In [38]:
A = np.array([[2, 1, 1], [0, 4, -6], [-2, 7, 2]])
b = np.array([5, -2, 9])
print("Matriz de coeficientes: ")
print(A)
print("Vector de valores por ecuacion")
print(b)

Matriz de coeficientes: 
[[ 2  1  1]
 [ 0  4 -6]
 [-2  7  2]]
Vector de valores por ecuacion
[ 5 -2  9]


In [39]:
X = ln.solve(A,b)
print("Vector de valores de solucion:")
print(X)

Vector de valores de solucion:
[ 1.25  1.3   1.2 ]


## Factorizacion QR ##
La descomposición o factorización QR de una matriz es una descomposición de la misma como producto de una matriz ortogonal por una triangular superior. Dentro de linalg la funcion para realizar esta operacion es _qr_ que recibe como primer argumento la matriz que se quiere factorizar.

Ejemplo:
```python
import numpy as np
a = np.array([[25, 35, 12, 4], [23, 74, 2, 64], [89, 4, 23, 56], [48, 17, 6, 99]])
import numpy.linalg as ln
q, r = ln.qr(a)
```

In [28]:
q, r = ln.qr(a)
print("q:")
print(q)
print("r:")
print(r)

q:
[[-0.23436241 -0.35230687  0.75173493  0.50581492]
 [-0.21561342 -0.87436864 -0.22790461 -0.37020241]
 [-0.83433019  0.33334033  0.16882729 -0.40530817]
 [-0.44997583 -0.01560705 -0.59535824  0.66545228]]
r:
[[-106.67239568  -35.14498738  -25.13302512 -106.00680643]
 [   0.          -75.96597832    1.59676546  -40.24686042]
 [   0.            0.            8.87588804  -61.06509338]
 [   0.            0.            0.           21.51282381]]


La funcion _qr_ retorna dos matrices: q como la matriz ortogonal de la factorizacion y r como la matriz triangular superior de la factorizacion.
Si se quiere verificar esta operacion se puede usar la funcion de numpy _matmul_ con la cual se pueden multiplicar dos matrices de forma sencilla
```python
c = np.matmul(q,r)
```

In [35]:
print("q x r")
print(np.matmul(q,r))

q x r
[[ 25.  35.  12.   4.]
 [ 23.  74.   2.  64.]
 [ 89.   4.  23.  56.]
 [ 48.  17.   6.  99.]]
