# Tutorial de la Librería LinAlg de Numpy #
### Diego Correa ###
### Jose Ortega ###

La librería **linalg** que se encuentra en **numpy** se especializa en algebra lineal con matrices y vectores provistos por numpy.

Importar las librerias necesarias

In [30]:
import numpy as np

In [31]:
import numpy.linalg as la

Definimos algunas matrices

In [32]:
a=np.array([[1,2],[3,4]])

In [33]:
b=np.array([2,3])

Función _det(a)_ recibe una matriz y calcula su determinante. 

Ejemplo:

In [34]:
la.det(a)

-2.0000000000000004

Funcion _inv(a)_ recibe una matriz singular (cuyo determinante sea diferente de cero) y calcula su inversa.

Ejemplo:

In [35]:
la.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Función _solve(a,b)_ recibe una matriz de nxn y un vector de nx1 y resuelve el sistema de ecuaciones que corresponde a dichos vectores.

Ejemplo:

In [36]:
la.solve(a,b)

array([-1. ,  1.5])

Función _matrix_rank(a)_ recibe una matriz y retorna el numero de columnas linealmente independientes.

Ejemplo:

In [37]:
la.matrix_rank(a)

2

Función _eig(a)_ recibe una matriz cuadrada y retorna los valores propios y vectores propios.

Ejemplo:

In [38]:
la.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Función _slogdet(a)_ recibe una matriz cudrada y retorna el signo y logaritmo natural del determinante de esta.

Ejemplo:

In [39]:
la.slogdet(a)

(-1.0, 0.6931471805599455)

Función _pinv(a)_

Calcula el pseudoinverso (Moore-Penrose) de una matriz.

Calcula el inverso generalizado de una matriz usando su descomposición de valores singulares (SVD) e incluyendo todos los grandes valores singulares.

Ejemplo:

In [40]:
la.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Función _norm(a)_ recibe una matriz a y retorna el vector norma de dicha matriz.

Ejemplo:

In [41]:
la.norm(a)

5.477225575051661