Tutorial de la Librería LinAlg de Numpy
Elaborado por:
Diego Alejandro Correa
Jose Ricardo Ortega

importar las librerias necesarias

In [30]:
import numpy as np

In [31]:
import numpy.linalg as la

Definimos algunas matrices

In [32]:
a=np.array([[1,2],[3,4]])

In [33]:
b=np.array([2,3])

Función det(a)
Recibe una matriz y calcula su determinante. 
Ejemplo:

In [34]:
la.det(a)

-2.0000000000000004

Funcion inv(a)
Recibe una matriz singular (cuyo determinante sea diferente de cero) y calcula su inversa. 
Ejemplo:

In [35]:
la.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Función solve(a,b)
Recibe una matriz de nxn y un vector de nx1 y resuelve el sistema de ecuaciones que corresponde a dichos vectores. 
Ejemplo:

In [36]:
la.solve(a,b)

array([-1. ,  1.5])

Función matrix_rank(a)
Recibe una matriz y retorna el numero de columnas linealmente independientes 
Ejemplo:

In [37]:
la.matrix_rank(a)

2

Función eig(a)
Recibe una matriz cuadrada y retorna los valores propios y vectores propios. 
Ejemplo:

In [38]:
la.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

Función slogdet(a)
Recibe una matriz cudrada y retorna el signo y logaritmo natural del determinante de esta. 
Ejemplo:

In [39]:
la.slogdet(a)

(-1.0, 0.6931471805599455)

Función pinv(a)
Calcula el pseudoinverso (Moore-Penrose) de una matriz.
Calcula el inverso generalizado de una matriz usando su descomposición de valores singulares (SVD) e incluyendo todos los grandes valores singulares.
Ejemplo:

In [40]:
la.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Función norm(a)
Recibe una matriz a y retorna el vector norma de dicha matriz. 
Ejemplo:

In [41]:
la.norm(a)

5.477225575051661